/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Turista.WiewBogota;

import Datos.GestorReservas;
import Modelo.Reserva;
import UI.Bogota;
import UI.MisReservas;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SARA
 */
public class RegisTuristaHotelWindsor extends javax.swing.JFrame {

    /**
     * Creates new form registuristabarranquilla
     */
    public RegisTuristaHotelWindsor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cbxTipoId = new javax.swing.JComboBox<>();
        txtDocumento = new javax.swing.JTextField();
        cbxLugar = new javax.swing.JComboBox<>();
        txtMotivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCalendarCheckIn = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jCalendarCheckOut = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Ingrese sus Datos Para Realizar Su Reserva");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 0, 410, 26);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        txtNombres.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtNombres.setText("Nombres:");
        jPanel1.add(txtNombres);
        txtNombres.setBounds(20, 30, 180, 23);

        txtApellidos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtApellidos.setText("Apellidos:");
        jPanel1.add(txtApellidos);
        txtApellidos.setBounds(20, 60, 180, 23);

        cbxTipoId.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbxTipoId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo De Identificacion", "C.C", "N.I.T", "Pasaporte", "Licencia De Conducir" }));
        jPanel1.add(cbxTipoId);
        cbxTipoId.setBounds(20, 90, 180, 23);

        txtDocumento.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtDocumento.setText("N° De Identificacion:");
        jPanel1.add(txtDocumento);
        txtDocumento.setBounds(20, 120, 180, 23);

        cbxLugar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        cbxLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Que lugar desea reservar:", "Habitacion", "Penthouse", "Salon de Eventos", "Restaurante", " " }));
        jPanel1.add(cbxLugar);
        cbxLugar.setBounds(310, 30, 200, 23);

        txtMotivo.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        txtMotivo.setText("Motivo de su reserva:");
        jPanel1.add(txtMotivo);
        txtMotivo.setBounds(310, 60, 200, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Check In:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 90, 57, 17);
        jPanel1.add(jCalendarCheckIn);
        jCalendarCheckIn.setBounds(380, 90, 90, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Check Out:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 120, 70, 17);
        jPanel1.add(jCalendarCheckOut);
        jCalendarCheckOut.setBounds(380, 120, 90, 22);

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("Vaciar");
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 220, 72, 24);

        Guardar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar);
        Guardar.setBounds(310, 220, 90, 24);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo (4).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 540, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 539, 260);

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 310, 86, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Bogota().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        String nombres = txtNombres.getText();
String apellidos = txtApellidos.getText();
String tipoId = (String) cbxTipoId.getSelectedItem();
String documento = txtDocumento.getText();
String lugar = (String) cbxLugar.getSelectedItem();
String motivo = txtMotivo.getText();
Date fechaCheckIn = jCalendarCheckIn.getDate();
Date fechaCheckOut = jCalendarCheckOut.getDate();

// Crear objeto Reserva
Reserva nuevaReserva = new Reserva(nombres, apellidos, tipoId, documento, lugar, motivo, fechaCheckIn, fechaCheckOut);

// Guardar con el gestor
GestorReservas gestor = new GestorReservas();
gestor.agregarReserva(nuevaReserva); // Esto guarda en JSON

// Actualizar tabla si la ventana está abierta
if (MisReservas.instanciaActiva != null) {
    MisReservas.instanciaActiva.cargarReservasEnTabla();
}

// Mostrar mensaje
JOptionPane.showMessageDialog(this, "Reserva guardada exitosamente.");
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotelWindsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotelWindsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotelWindsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisTuristaHotelWindsor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisTuristaHotelWindsor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> cbxLugar;
    private javax.swing.JComboBox<String> cbxTipoId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jCalendarCheckIn;
    private com.toedter.calendar.JDateChooser jCalendarCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
